# Generated by Django 4.1.7 on 2023-04-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_category_note_user_delete_snippet_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='lastUpdated',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
