# Generated by Django 3.2.8 on 2023-04-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_alter_note_created_alter_note_lastupdated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
